apiVersion: batch/v1
kind: CronJob
metadata:
  name: ping-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 5
      parallelism: 5
      template:
        spec:
          containers:
          - name: ping
            image: nhphat1997/ping:latest
          restartPolicy: Never
