apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pong-deploy
  name: pong-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: pong-deploy
  type: ClusterIP
status:
  loadBalancer: {}
